openapi: 3.0.2
info:
  title: Email-managment
  version: 1.0.0
paths:
  /e-mails:
    get:
      parameters:
        - examples:
            session:
              value: "49"
          name: bearerAuth
          description: sessionId
          schema:
            type: integer
          in: header
          required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Emails"
              examples:
                emails:
                  value:
                    - id: 46
                      name: some text
                      email: some text
                      content: some text
                    - id: 52
                      name: some text
                      email: some text
                      content: some text
          description: returns list on emails
        "401":
          headers:
            sessionId:
              schema:
                type: integer
              examples:
                sessionID:
                  value: "98"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
              examples:
                error:
                  value:
                    error: You need to login
          description: Unouthorized
        "403":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
              examples:
                error:
                  value: forbidden request
          description: something went wrong
      security:
        - bearerAuth: []
      description: get emails
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/postEmail"
            examples:
              postEmail:
                value:
                  id: 68
                  name: some text
                  email: some text
                  content: some text
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/postEmail"
              examples:
                postEmail:
                  value:
                    id: 81
                    name: some text
                    email: some text
                    content: some text
          description: created
      security:
        - bearerAuth: []
      description: post emails
    delete:
      parameters:
        - name: bearerAuth
          description: delete email
          schema: {}
          in: header
          required: true
      responses:
        "201":
          content:
            application/json:
              examples:
                success:
                  value: "success: true"
          description: "success: true"
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
              examples:
                Unauthorized:
                  value:
                    error: some text
          description: Unauthorized
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
              examples:
                Not found:
                  value:
                    error: some text
          description: no email found
      security:
        - bearerAuth: []
      description: delete email
  /sessions:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/postSessions"
            examples:
              post sessions:
                value:
                  username: some text
                  password: some text
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/postSessionsResponse"
              examples:
                response:
                  value:
                    sessionId: 22
                    success: true
          description: created
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
              examples:
                error:
                  value:
                    error: unouthorized
          description: Unauthorized
components:
  schemas:
    postSessions:
      title: Root Type for postSessions
      description: post sessions
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      example:
        username: username
        password: password
    postSessionsResponse:
      title: Root Type for postSessionsResponse
      description: get sessions
      type: object
      properties:
        sessionId:
          format: int32
          type: integer
        success:
          type: boolean
      example:
        sessionId: 77169636
        success: true
    error:
      title: Root Type for error
      description: error message
      type: object
      properties:
        error:
          type: string
      example:
        error: unouthorized
    Emails:
      title: Root Type for getEmails
      description: get emails
      type: object
      properties:
        id:
          format: int32
          type: integer
        name:
          type: string
        email:
          type: string
        content:
          type: string
      example:
        id: 1
        name: John
        email: john@example.com
        content: "Hello, world!"
    postEmail:
      title: Root Type for postEmail
      description: post e-mail
      type: object
      properties:
        id:
          format: int32
          type: integer
        name:
          type: string
        email:
          type: string
        content:
          type: string
      example:
        id: 2
        name: Mihkel
        email: mihkel@example.com
        content: tere mis toimub
  responses:
    e-mails:
      description: get emails
  securitySchemes:
    bearerAuth:
      scheme: bearer
      type: http
